server {
        root /var/www/{{ item.key | string | regex_search("[a-z]+") }};
        autoindex off;
        charset UTF-8;
        index index.php index.html index.htm;
        client_max_body_size 20M;

        server_name {{ item.value }} www.{{ item.value }};

        location / {
                try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/{{ item.value }}/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/{{ item.value }}/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.{{ item.value }}) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = {{ item.value }}) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;

        server_name {{ item.value }} www.{{ item.value }};
    return 404; # managed by Certbot




}